import { PageHeading } from '@/components/common/PageHeading'
import { Title } from '@/components/common/Title'
import { Heading } from '@chakra-ui/react'
import { useSession } from 'next-auth/react'
import useTranslation from 'next-translate/useTranslation'
import { NextPageWithLayout } from './_app'
/*
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Impulzus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      </main>
    </>
  )
}*/

const Page: NextPageWithLayout = () => {
  const { data: session } = useSession()
  const { t } = useTranslation('common')

  console.log(session)
  return (
    <>
      <Title />
      <PageHeading text={t('title')} />
      <Heading>Üdvözlünk az Impulzus oldalán!</Heading>
    </>
  )
}

export default Page
